#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_bus_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_bus_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_bus_AWADDR", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_bus_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_bus_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_bus_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_bus_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_bus_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_bus_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_bus_ARADDR", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_bus_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_bus_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_bus_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_bus_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_bus_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_bus_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_bus_BRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("interrupt", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_Layer_Neurons_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_Layer_Neurons_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_Layer_Neurons_AWADDR", 14, hls_in, -1, "", "", 1),
	Port_Property("s_axi_Layer_Neurons_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_Layer_Neurons_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_Layer_Neurons_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_Layer_Neurons_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_Layer_Neurons_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_Layer_Neurons_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_Layer_Neurons_ARADDR", 14, hls_in, -1, "", "", 1),
	Port_Property("s_axi_Layer_Neurons_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_Layer_Neurons_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_Layer_Neurons_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_Layer_Neurons_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_Layer_Neurons_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_Layer_Neurons_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_Layer_Neurons_BRESP", 2, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "cnn_lenet";
