-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity calculateLayer3_generic_tanh_double_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    t_in : IN STD_LOGIC_VECTOR (63 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of calculateLayer3_generic_tanh_double_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_pp0_stage5 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_pp0_stage6 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_pp0_stage7 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv64_3FF0000000000000 : STD_LOGIC_VECTOR (63 downto 0) := "0011111111110000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_BFF0000000000000 : STD_LOGIC_VECTOR (63 downto 0) := "1011111111110000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_4000000000000000 : STD_LOGIC_VECTOR (63 downto 0) := "0100000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_4036000000000000 : STD_LOGIC_VECTOR (63 downto 0) := "0100000000110110000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv11_3C8 : STD_LOGIC_VECTOR (10 downto 0) := "01111001000";
    constant ap_const_lv52_0 : STD_LOGIC_VECTOR (51 downto 0) := "0000000000000000000000000000000000000000000000000000";
    constant ap_const_lv11_3FF : STD_LOGIC_VECTOR (10 downto 0) := "01111111111";
    constant ap_const_lv64_8000000000000000 : STD_LOGIC_VECTOR (63 downto 0) := "1000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv11_3E4 : STD_LOGIC_VECTOR (10 downto 0) := "01111100100";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv11_3E5 : STD_LOGIC_VECTOR (10 downto 0) := "01111100101";
    constant ap_const_lv64_7FFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (63 downto 0) := "0111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage7 : signal is "none";
    signal ap_block_pp0_stage7_subdone : BOOLEAN;
    signal expx_reg_60 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_114_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal reg_124 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_pp0_stage4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage4 : signal is "none";
    signal ap_block_pp0_stage4_11001 : BOOLEAN;
    signal icmp_ln36_reg_367 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln36_reg_367_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_reg_371 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_reg_371_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln46_reg_375 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln46_reg_375_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_384 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_384_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln54_reg_388 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln54_reg_388_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal ap_predicate_pred99_state37 : BOOLEAN;
    signal ap_predicate_pred113_state37 : BOOLEAN;
    signal din_sign_reg_344 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal din_sign_reg_344_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal din_sign_reg_344_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal din_sign_reg_344_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal din_sign_reg_344_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal din_exp_fu_142_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal din_exp_reg_349 : STD_LOGIC_VECTOR (10 downto 0);
    signal t_fu_160_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal t_reg_354 : STD_LOGIC_VECTOR (63 downto 0);
    signal abst_in_fu_168_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal abst_in_reg_359 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln36_fu_174_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln36_reg_367_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln36_reg_367_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln36_reg_367_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_fu_180_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_reg_371_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_reg_371_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_reg_371_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln46_fu_198_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln46_reg_375_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln46_reg_375_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln46_reg_375_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_fu_204_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_379 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_379_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_379_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_379_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_379_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_119_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal tmp_2_reg_384_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_384_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_384_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln54_fu_210_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln54_reg_388_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln54_reg_388_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln54_reg_388_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln55_fu_220_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_100_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_reg_398 : STD_LOGIC_VECTOR (63 downto 0);
    signal x_reg_403 : STD_LOGIC_VECTOR (63 downto 0);
    signal x_3_fu_225_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal x_3_reg_408 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_pp0_stage5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage5 : signal is "none";
    signal ap_block_pp0_stage5_11001 : BOOLEAN;
    signal and_ln9_1_fu_271_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln9_1_reg_415 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln9_1_reg_415_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln10_1_fu_295_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln10_1_reg_419 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln10_1_reg_419_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_110_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage7_11001 : BOOLEAN;
    signal grp_exp_generic_double_s_fu_89_ap_return : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_4_reg_428 : STD_LOGIC_VECTOR (63 downto 0);
    signal add2_reg_438 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_pp0_stage6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage6 : signal is "none";
    signal ap_block_pp0_stage6_11001 : BOOLEAN;
    signal bitcast_ln66_1_fu_311_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln38_fu_316_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal grp_exp_generic_double_s_fu_89_ap_start : STD_LOGIC;
    signal grp_exp_generic_double_s_fu_89_ap_done : STD_LOGIC;
    signal grp_exp_generic_double_s_fu_89_ap_idle : STD_LOGIC;
    signal grp_exp_generic_double_s_fu_89_ap_ready : STD_LOGIC;
    signal ap_phi_reg_pp0_iter0_expx_reg_60 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_reg_pp0_iter1_expx_reg_60 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_reg_pp0_iter2_expx_reg_60 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_predicate_pred269_state18 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal ap_phi_mux_resultf_3_phi_fu_76_p10 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_reg_pp0_iter0_resultf_3_reg_72 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_reg_pp0_iter1_resultf_3_reg_72 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_reg_pp0_iter2_resultf_3_reg_72 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_reg_pp0_iter3_resultf_3_reg_72 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_reg_pp0_iter4_resultf_3_reg_72 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_reg_pp0_iter5_resultf_3_reg_72 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_exp_generic_double_s_fu_89_ap_start_reg : STD_LOGIC := '0';
    signal ap_predicate_op94_call_state7_state6 : BOOLEAN;
    signal ap_block_pp0_stage6 : BOOLEAN;
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal ap_block_pp0_stage4 : BOOLEAN;
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal grp_fu_100_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_100_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal ap_block_pp0_stage5 : BOOLEAN;
    signal grp_fu_114_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage7 : BOOLEAN;
    signal ap_predicate_pred458_state24 : BOOLEAN;
    signal ap_predicate_pred463_state24 : BOOLEAN;
    signal grp_fu_119_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal data_fu_130_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln479_fu_156_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal din_sig_fu_152_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln46_fu_186_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_1_fu_192_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln55_fu_215_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal data_1_fu_231_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal xs_exp_1_fu_243_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln9_fu_253_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln9_1_fu_259_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln9_fu_265_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xs_sign_fu_235_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln10_fu_277_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln10_fu_289_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_fu_283_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln66_fu_301_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln66_fu_305_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln83_fu_323_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln83_fu_327_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln83_1_fu_333_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_100_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_block_pp0_stage2_00001 : BOOLEAN;
    signal ap_block_pp0_stage6_00001 : BOOLEAN;
    signal ap_predicate_pred363_state15 : BOOLEAN;
    signal ap_block_pp0_stage3_00001 : BOOLEAN;
    signal ap_block_pp0_stage1_00001 : BOOLEAN;
    signal ap_block_pp0_stage5_00001 : BOOLEAN;
    signal ap_predicate_pred99_state38 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_idle_pp0_0to4 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_idle_pp0_1to5 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal ap_block_pp0_stage5_subdone : BOOLEAN;
    signal ap_block_pp0_stage6_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_319 : BOOLEAN;
    signal ap_condition_254 : BOOLEAN;
    signal ap_condition_314 : BOOLEAN;
    signal ap_condition_449 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component calculateLayer3_exp_generic_double_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        x : IN STD_LOGIC_VECTOR (63 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component calculateLayer3_dadddsub_64ns_64ns_64_4_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        opcode : IN STD_LOGIC_VECTOR (1 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component calculateLayer3_dmul_64ns_64ns_64_4_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component calculateLayer3_ddiv_64ns_64ns_64_14_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component calculateLayer3_dcmp_64ns_64ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    grp_exp_generic_double_s_fu_89 : component calculateLayer3_exp_generic_double_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_exp_generic_double_s_fu_89_ap_start,
        ap_done => grp_exp_generic_double_s_fu_89_ap_done,
        ap_idle => grp_exp_generic_double_s_fu_89_ap_idle,
        ap_ready => grp_exp_generic_double_s_fu_89_ap_ready,
        x => x_3_reg_408,
        ap_return => grp_exp_generic_double_s_fu_89_ap_return);

    dadddsub_64ns_64ns_64_4_full_dsp_1_U15 : component calculateLayer3_dadddsub_64ns_64ns_64_4_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_100_p0,
        din1 => grp_fu_100_p1,
        opcode => grp_fu_100_opcode,
        ce => ap_const_logic_1,
        dout => grp_fu_100_p2);

    dmul_64ns_64ns_64_4_max_dsp_1_U16 : component calculateLayer3_dmul_64ns_64ns_64_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => abst_in_reg_359,
        din1 => add_reg_398,
        ce => ap_const_logic_1,
        dout => grp_fu_110_p2);

    ddiv_64ns_64ns_64_14_no_dsp_1_U17 : component calculateLayer3_ddiv_64ns_64ns_64_14_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 14,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_114_p0,
        din1 => add2_reg_438,
        ce => ap_const_logic_1,
        dout => grp_fu_114_p2);

    dcmp_64ns_64ns_1_2_no_dsp_1_U18 : component calculateLayer3_dcmp_64ns_64ns_1_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_119_p0,
        din1 => ap_const_lv64_4036000000000000,
        ce => ap_const_logic_1,
        opcode => ap_const_lv5_4,
        dout => grp_fu_119_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage7_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage7_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage7_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage7_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage7_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    grp_exp_generic_double_s_fu_89_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_exp_generic_double_s_fu_89_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_predicate_op94_call_state7_state6 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
                    grp_exp_generic_double_s_fu_89_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_exp_generic_double_s_fu_89_ap_ready = ap_const_logic_1)) then 
                    grp_exp_generic_double_s_fu_89_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_resultf_3_reg_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_254)) then
                if ((ap_const_boolean_1 = ap_condition_319)) then 
                    ap_phi_reg_pp0_iter1_resultf_3_reg_72 <= grp_fu_110_p2;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_resultf_3_reg_72 <= ap_phi_reg_pp0_iter0_resultf_3_reg_72;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_expx_reg_60_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_predicate_pred269_state18 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_phi_reg_pp0_iter2_expx_reg_60 <= grp_fu_100_p2;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                ap_phi_reg_pp0_iter2_expx_reg_60 <= ap_phi_reg_pp0_iter1_expx_reg_60;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter4_resultf_3_reg_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_predicate_pred113_state37 = ap_const_boolean_1))) then 
                ap_phi_reg_pp0_iter4_resultf_3_reg_72 <= grp_fu_114_p2;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                ap_phi_reg_pp0_iter4_resultf_3_reg_72 <= ap_phi_reg_pp0_iter3_resultf_3_reg_72;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter5_resultf_3_reg_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_314)) then
                if ((icmp_ln36_reg_367_pp0_iter4_reg = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter5_resultf_3_reg_72 <= select_ln38_fu_316_p3;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter5_resultf_3_reg_72 <= ap_phi_reg_pp0_iter4_resultf_3_reg_72;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                    abst_in_reg_359(62 downto 0) <= abst_in_fu_168_p1(62 downto 0);
                and_ln46_reg_375 <= and_ln46_fu_198_p2;
                and_ln46_reg_375_pp0_iter1_reg <= and_ln46_reg_375;
                and_ln46_reg_375_pp0_iter2_reg <= and_ln46_reg_375_pp0_iter1_reg;
                and_ln46_reg_375_pp0_iter3_reg <= and_ln46_reg_375_pp0_iter2_reg;
                and_ln46_reg_375_pp0_iter4_reg <= and_ln46_reg_375_pp0_iter3_reg;
                    ap_predicate_pred269_state18 <= ((ap_const_lv1_0 = and_ln10_1_reg_419_pp0_iter1_reg) and (ap_const_lv1_0 = and_ln9_1_reg_415_pp0_iter1_reg) and (ap_const_lv1_0 = and_ln46_reg_375_pp0_iter1_reg) and (tmp_2_reg_384_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln45_reg_371_pp0_iter1_reg = ap_const_lv1_0) and (icmp_ln36_reg_367_pp0_iter1_reg = ap_const_lv1_0));
                din_exp_reg_349 <= data_fu_130_p1(62 downto 52);
                din_sign_reg_344 <= data_fu_130_p1(63 downto 63);
                din_sign_reg_344_pp0_iter1_reg <= din_sign_reg_344;
                din_sign_reg_344_pp0_iter2_reg <= din_sign_reg_344_pp0_iter1_reg;
                din_sign_reg_344_pp0_iter3_reg <= din_sign_reg_344_pp0_iter2_reg;
                din_sign_reg_344_pp0_iter4_reg <= din_sign_reg_344_pp0_iter3_reg;
                icmp_ln36_reg_367 <= icmp_ln36_fu_174_p2;
                icmp_ln36_reg_367_pp0_iter1_reg <= icmp_ln36_reg_367;
                icmp_ln36_reg_367_pp0_iter2_reg <= icmp_ln36_reg_367_pp0_iter1_reg;
                icmp_ln36_reg_367_pp0_iter3_reg <= icmp_ln36_reg_367_pp0_iter2_reg;
                icmp_ln36_reg_367_pp0_iter4_reg <= icmp_ln36_reg_367_pp0_iter3_reg;
                icmp_ln38_reg_379 <= icmp_ln38_fu_204_p2;
                icmp_ln38_reg_379_pp0_iter1_reg <= icmp_ln38_reg_379;
                icmp_ln38_reg_379_pp0_iter2_reg <= icmp_ln38_reg_379_pp0_iter1_reg;
                icmp_ln38_reg_379_pp0_iter3_reg <= icmp_ln38_reg_379_pp0_iter2_reg;
                icmp_ln38_reg_379_pp0_iter4_reg <= icmp_ln38_reg_379_pp0_iter3_reg;
                icmp_ln45_reg_371 <= icmp_ln45_fu_180_p2;
                icmp_ln45_reg_371_pp0_iter1_reg <= icmp_ln45_reg_371;
                icmp_ln45_reg_371_pp0_iter2_reg <= icmp_ln45_reg_371_pp0_iter1_reg;
                icmp_ln45_reg_371_pp0_iter3_reg <= icmp_ln45_reg_371_pp0_iter2_reg;
                icmp_ln45_reg_371_pp0_iter4_reg <= icmp_ln45_reg_371_pp0_iter3_reg;
                    t_reg_354(62 downto 0) <= t_fu_160_p3(62 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then
                add2_reg_438 <= grp_fu_100_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                add_reg_398 <= grp_fu_100_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then
                and_ln10_1_reg_419 <= and_ln10_1_fu_295_p2;
                and_ln10_1_reg_419_pp0_iter1_reg <= and_ln10_1_reg_419;
                and_ln9_1_reg_415 <= and_ln9_1_fu_271_p2;
                and_ln9_1_reg_415_pp0_iter1_reg <= and_ln9_1_reg_415;
                    ap_predicate_pred363_state15 <= ((ap_const_lv1_0 = and_ln10_1_reg_419) and (ap_const_lv1_0 = and_ln9_1_reg_415) and (ap_const_lv1_0 = and_ln46_reg_375_pp0_iter1_reg) and (tmp_2_reg_384_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln45_reg_371_pp0_iter1_reg = ap_const_lv1_0) and (icmp_ln36_reg_367_pp0_iter1_reg = ap_const_lv1_0));
                tmp_4_reg_428 <= grp_exp_generic_double_s_fu_89_ap_return;
                x_3_reg_408 <= x_3_fu_225_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_lv1_1 = and_ln10_1_fu_295_p2) and (tmp_2_reg_384 = ap_const_lv1_1) and (icmp_ln45_reg_371 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln46_reg_375) and (ap_const_lv1_0 = and_ln9_1_fu_271_p2) and (icmp_ln36_reg_367 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_const_lv1_1 = and_ln9_1_fu_271_p2) and (tmp_2_reg_384 = ap_const_lv1_1) and (icmp_ln45_reg_371 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln46_reg_375) and (icmp_ln36_reg_367 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)))) then
                ap_phi_reg_pp0_iter0_expx_reg_60 <= x_3_fu_225_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then
                ap_phi_reg_pp0_iter1_expx_reg_60 <= ap_phi_reg_pp0_iter0_expx_reg_60;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then
                ap_phi_reg_pp0_iter2_resultf_3_reg_72 <= ap_phi_reg_pp0_iter1_resultf_3_reg_72;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then
                ap_phi_reg_pp0_iter3_resultf_3_reg_72 <= ap_phi_reg_pp0_iter2_resultf_3_reg_72;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                    ap_predicate_pred113_state37 <= ((icmp_ln54_reg_388_pp0_iter4_reg = ap_const_lv1_1) and (tmp_2_reg_384_pp0_iter4_reg = ap_const_lv1_1) and (icmp_ln45_reg_371_pp0_iter4_reg = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln46_reg_375_pp0_iter4_reg) and (icmp_ln36_reg_367_pp0_iter4_reg = ap_const_lv1_0));
                    ap_predicate_pred99_state37 <= ((icmp_ln54_reg_388_pp0_iter4_reg = ap_const_lv1_0) and (tmp_2_reg_384_pp0_iter4_reg = ap_const_lv1_1) and (icmp_ln45_reg_371_pp0_iter4_reg = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln46_reg_375_pp0_iter4_reg) and (icmp_ln36_reg_367_pp0_iter4_reg = ap_const_lv1_0));
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then
                    ap_predicate_pred458_state24 <= ((ap_const_lv1_0 = and_ln46_reg_375_pp0_iter2_reg) and (icmp_ln54_reg_388_pp0_iter2_reg = ap_const_lv1_0) and (tmp_2_reg_384_pp0_iter2_reg = ap_const_lv1_1) and (icmp_ln45_reg_371_pp0_iter2_reg = ap_const_lv1_0) and (icmp_ln36_reg_367_pp0_iter2_reg = ap_const_lv1_0));
                    ap_predicate_pred463_state24 <= ((ap_const_lv1_0 = and_ln46_reg_375_pp0_iter2_reg) and (icmp_ln54_reg_388_pp0_iter2_reg = ap_const_lv1_1) and (tmp_2_reg_384_pp0_iter2_reg = ap_const_lv1_1) and (icmp_ln45_reg_371_pp0_iter2_reg = ap_const_lv1_0) and (icmp_ln36_reg_367_pp0_iter2_reg = ap_const_lv1_0));
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then
                    ap_predicate_pred99_state38 <= ((icmp_ln54_reg_388_pp0_iter4_reg = ap_const_lv1_0) and (tmp_2_reg_384_pp0_iter4_reg = ap_const_lv1_1) and (icmp_ln45_reg_371_pp0_iter4_reg = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln46_reg_375_pp0_iter4_reg) and (icmp_ln36_reg_367_pp0_iter4_reg = ap_const_lv1_0));
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                expx_reg_60 <= ap_phi_reg_pp0_iter2_expx_reg_60;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                icmp_ln54_reg_388 <= icmp_ln54_fu_210_p2;
                icmp_ln54_reg_388_pp0_iter1_reg <= icmp_ln54_reg_388;
                icmp_ln54_reg_388_pp0_iter2_reg <= icmp_ln54_reg_388_pp0_iter1_reg;
                icmp_ln54_reg_388_pp0_iter3_reg <= icmp_ln54_reg_388_pp0_iter2_reg;
                icmp_ln54_reg_388_pp0_iter4_reg <= icmp_ln54_reg_388_pp0_iter3_reg;
                tmp_2_reg_384 <= grp_fu_119_p2;
                tmp_2_reg_384_pp0_iter1_reg <= tmp_2_reg_384;
                tmp_2_reg_384_pp0_iter2_reg <= tmp_2_reg_384_pp0_iter1_reg;
                tmp_2_reg_384_pp0_iter3_reg <= tmp_2_reg_384_pp0_iter2_reg;
                tmp_2_reg_384_pp0_iter4_reg <= tmp_2_reg_384_pp0_iter3_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_predicate_pred113_state37 = ap_const_boolean_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_predicate_pred99_state37 = ap_const_boolean_1)))) then
                reg_124 <= grp_fu_114_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then
                x_reg_403 <= grp_fu_100_p2;
            end if;
        end if;
    end process;
    t_reg_354(63) <= '0';
    abst_in_reg_359(63) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_block_pp0_stage7_subdone, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0, ap_idle_pp0_1to5, ap_block_pp0_stage1_subdone, ap_block_pp0_stage2_subdone, ap_block_pp0_stage3_subdone, ap_block_pp0_stage4_subdone, ap_block_pp0_stage5_subdone, ap_block_pp0_stage6_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_idle_pp0_1to5 = ap_const_logic_1) and (ap_start = ap_const_logic_0))) and (ap_reset_idle_pp0 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                elsif (((ap_reset_idle_pp0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when ap_ST_fsm_pp0_stage5 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage5_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                end if;
            when ap_ST_fsm_pp0_stage6 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage6_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                end if;
            when ap_ST_fsm_pp0_stage7 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage7_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    abst_in_fu_168_p1 <= t_fu_160_p3;
    and_ln10_1_fu_295_p2 <= (icmp_ln10_fu_283_p2 and and_ln10_fu_289_p2);
    and_ln10_fu_289_p2 <= (xor_ln10_fu_277_p2 and icmp_ln9_1_fu_259_p2);
    and_ln46_fu_198_p2 <= (icmp_ln46_fu_186_p2 and icmp_ln46_1_fu_192_p2);
    and_ln9_1_fu_271_p2 <= (xs_sign_fu_235_p3 and and_ln9_fu_265_p2);
    and_ln9_fu_265_p2 <= (icmp_ln9_fu_253_p2 and icmp_ln9_1_fu_259_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage4 <= ap_CS_fsm(4);
    ap_CS_fsm_pp0_stage5 <= ap_CS_fsm(5);
    ap_CS_fsm_pp0_stage6 <= ap_CS_fsm(6);
    ap_CS_fsm_pp0_stage7 <= ap_CS_fsm(7);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage6_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage6_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage6_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage7_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage7_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_254_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage7, ap_block_pp0_stage7_11001)
    begin
                ap_condition_254 <= ((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7));
    end process;


    ap_condition_314_assign_proc : process(ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage7, ap_block_pp0_stage7_11001)
    begin
                ap_condition_314 <= ((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7));
    end process;


    ap_condition_319_assign_proc : process(icmp_ln36_reg_367, icmp_ln45_reg_371, and_ln46_reg_375)
    begin
                ap_condition_319 <= (((icmp_ln45_reg_371 = ap_const_lv1_1) and (icmp_ln36_reg_367 = ap_const_lv1_0)) or ((ap_const_lv1_1 = and_ln46_reg_375) and (icmp_ln36_reg_367 = ap_const_lv1_0)));
    end process;


    ap_condition_449_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage7, ap_block_pp0_stage7)
    begin
                ap_condition_449 <= ((ap_const_boolean_0 = ap_block_pp0_stage7) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to4_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to4 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to5_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to5 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to5 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_resultf_3_phi_fu_76_p10_assign_proc : process(icmp_ln36_reg_367_pp0_iter4_reg, icmp_ln45_reg_371_pp0_iter4_reg, and_ln46_reg_375_pp0_iter4_reg, tmp_2_reg_384_pp0_iter4_reg, icmp_ln54_reg_388_pp0_iter4_reg, grp_fu_100_p2, ap_phi_reg_pp0_iter5_resultf_3_reg_72)
    begin
        if (((icmp_ln54_reg_388_pp0_iter4_reg = ap_const_lv1_0) and (tmp_2_reg_384_pp0_iter4_reg = ap_const_lv1_1) and (icmp_ln45_reg_371_pp0_iter4_reg = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln46_reg_375_pp0_iter4_reg) and (icmp_ln36_reg_367_pp0_iter4_reg = ap_const_lv1_0))) then 
            ap_phi_mux_resultf_3_phi_fu_76_p10 <= grp_fu_100_p2;
        else 
            ap_phi_mux_resultf_3_phi_fu_76_p10 <= ap_phi_reg_pp0_iter5_resultf_3_reg_72;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_resultf_3_reg_72 <= ap_const_lv64_3FF0000000000000;

    ap_predicate_op94_call_state7_state6_assign_proc : process(icmp_ln36_reg_367, icmp_ln45_reg_371, and_ln46_reg_375, tmp_2_reg_384, and_ln9_1_fu_271_p2, and_ln10_1_fu_295_p2)
    begin
                ap_predicate_op94_call_state7_state6 <= ((tmp_2_reg_384 = ap_const_lv1_1) and (icmp_ln45_reg_371 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln46_reg_375) and (ap_const_lv1_0 = and_ln10_1_fu_295_p2) and (ap_const_lv1_0 = and_ln9_1_fu_271_p2) and (icmp_ln36_reg_367 = ap_const_lv1_0));
    end process;


    ap_ready_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage7, ap_block_pp0_stage7_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage7_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to4)
    begin
        if (((ap_idle_pp0_0to4 = ap_const_logic_1) and (ap_start = ap_const_logic_0))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= 
        bitcast_ln83_1_fu_333_p1 when (din_sign_reg_344_pp0_iter4_reg(0) = '1') else 
        ap_phi_mux_resultf_3_phi_fu_76_p10;
    bitcast_ln55_fu_220_p1 <= or_ln55_fu_215_p2;
    bitcast_ln66_1_fu_311_p1 <= xor_ln66_fu_305_p2;
    bitcast_ln66_fu_301_p1 <= expx_reg_60;
    bitcast_ln83_1_fu_333_p1 <= xor_ln83_fu_327_p2;
    bitcast_ln83_fu_323_p1 <= ap_phi_mux_resultf_3_phi_fu_76_p10;
    data_1_fu_231_p1 <= x_3_fu_225_p3;
    data_fu_130_p1 <= t_in;
    din_exp_fu_142_p4 <= data_fu_130_p1(62 downto 52);
    din_sig_fu_152_p1 <= data_fu_130_p1(52 - 1 downto 0);
    grp_exp_generic_double_s_fu_89_ap_start <= grp_exp_generic_double_s_fu_89_ap_start_reg;

    grp_fu_100_opcode_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter4, icmp_ln36_reg_367, icmp_ln45_reg_371, and_ln46_reg_375, tmp_2_reg_384, icmp_ln54_reg_388, ap_CS_fsm_pp0_stage3, icmp_ln36_fu_174_p2, icmp_ln36_reg_367_pp0_iter2_reg, icmp_ln45_fu_180_p2, icmp_ln45_reg_371_pp0_iter2_reg, and_ln46_fu_198_p2, and_ln46_reg_375_pp0_iter2_reg, grp_fu_119_p2, ap_CS_fsm_pp0_stage1, tmp_2_reg_384_pp0_iter2_reg, ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage6, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0_00001, ap_block_pp0_stage2_00001, ap_block_pp0_stage6_00001, ap_predicate_pred363_state15, ap_block_pp0_stage3_00001, ap_block_pp0_stage1_00001, ap_block_pp0_stage5_00001, ap_predicate_pred99_state38)
    begin
        if ((((ap_predicate_pred99_state38 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage5_00001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((icmp_ln45_reg_371 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln46_reg_375) and (icmp_ln36_reg_367 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_00001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (grp_fu_119_p2 = ap_const_lv1_1)))) then 
            grp_fu_100_opcode <= ap_const_lv2_1;
        elsif ((((ap_predicate_pred363_state15 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage6_00001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((icmp_ln54_reg_388 = ap_const_lv1_0) and (tmp_2_reg_384 = ap_const_lv1_1) and (icmp_ln45_reg_371 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln46_reg_375) and (icmp_ln36_reg_367 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_00001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_00001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (((icmp_ln45_fu_180_p2 = ap_const_lv1_1) and (icmp_ln36_fu_174_p2 = ap_const_lv1_0)) or ((ap_const_lv1_1 = and_ln46_fu_198_p2) and (icmp_ln36_fu_174_p2 = ap_const_lv1_0)))) or ((ap_const_lv1_0 = and_ln46_reg_375_pp0_iter2_reg) and (ap_const_boolean_0 = ap_block_pp0_stage3_00001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) 
    and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (tmp_2_reg_384_pp0_iter2_reg = ap_const_lv1_1) and (icmp_ln45_reg_371_pp0_iter2_reg = ap_const_lv1_0) and (icmp_ln36_reg_367_pp0_iter2_reg = ap_const_lv1_0)))) then 
            grp_fu_100_opcode <= ap_const_lv2_0;
        else 
            grp_fu_100_opcode <= "XX";
        end if; 
    end process;


    grp_fu_100_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter4, expx_reg_60, ap_CS_fsm_pp0_stage3, abst_in_fu_168_p1, abst_in_reg_359, ap_CS_fsm_pp0_stage1, bitcast_ln55_fu_220_p1, ap_CS_fsm_pp0_stage5, tmp_4_reg_428, ap_CS_fsm_pp0_stage6, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage6, ap_block_pp0_stage3, ap_block_pp0_stage2, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage5)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage5) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
            grp_fu_100_p0 <= ap_const_lv64_3FF0000000000000;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            grp_fu_100_p0 <= expx_reg_60;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage6) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then 
            grp_fu_100_p0 <= tmp_4_reg_428;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            grp_fu_100_p0 <= abst_in_reg_359;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            grp_fu_100_p0 <= bitcast_ln55_fu_220_p1;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_100_p0 <= abst_in_fu_168_p1;
        else 
            grp_fu_100_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_100_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter4, reg_124, ap_CS_fsm_pp0_stage3, abst_in_reg_359, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage6, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage6, ap_block_pp0_stage3, ap_block_pp0_stage2, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage5)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage5) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
            grp_fu_100_p1 <= reg_124;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            grp_fu_100_p1 <= ap_const_lv64_4000000000000000;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage6) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then 
            grp_fu_100_p1 <= ap_const_lv64_BFF0000000000000;
        elsif ((((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)))) then 
            grp_fu_100_p1 <= abst_in_reg_359;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_100_p1 <= ap_const_lv64_3FF0000000000000;
        else 
            grp_fu_100_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_114_p0_assign_proc : process(bitcast_ln66_1_fu_311_p1, ap_predicate_pred458_state24, ap_predicate_pred463_state24, ap_condition_449)
    begin
        if ((ap_const_boolean_1 = ap_condition_449)) then
            if ((ap_predicate_pred463_state24 = ap_const_boolean_1)) then 
                grp_fu_114_p0 <= bitcast_ln66_1_fu_311_p1;
            elsif ((ap_predicate_pred458_state24 = ap_const_boolean_1)) then 
                grp_fu_114_p0 <= ap_const_lv64_4000000000000000;
            else 
                grp_fu_114_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_fu_114_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_fu_119_p0 <= t_fu_160_p3;
    icmp_ln10_fu_283_p2 <= "1" when (unsigned(xs_exp_1_fu_243_p4) < unsigned(ap_const_lv11_3E5)) else "0";
    icmp_ln36_fu_174_p2 <= "1" when (din_exp_fu_142_p4 = ap_const_lv11_7FF) else "0";
    icmp_ln38_fu_204_p2 <= "0" when (din_sig_fu_152_p1 = ap_const_lv52_0) else "1";
    icmp_ln45_fu_180_p2 <= "1" when (unsigned(din_exp_fu_142_p4) < unsigned(ap_const_lv11_3C8)) else "0";
    icmp_ln46_1_fu_192_p2 <= "1" when (din_sig_fu_152_p1 = ap_const_lv52_0) else "0";
    icmp_ln46_fu_186_p2 <= "1" when (din_exp_fu_142_p4 = ap_const_lv11_3C8) else "0";
    icmp_ln54_fu_210_p2 <= "1" when (unsigned(din_exp_reg_349) < unsigned(ap_const_lv11_3FF)) else "0";
    icmp_ln9_1_fu_259_p2 <= "0" when (xs_exp_1_fu_243_p4 = ap_const_lv11_0) else "1";
    icmp_ln9_fu_253_p2 <= "1" when (unsigned(xs_exp_1_fu_243_p4) < unsigned(ap_const_lv11_3E4)) else "0";
    or_ln55_fu_215_p2 <= (t_reg_354 or ap_const_lv64_8000000000000000);
    select_ln38_fu_316_p3 <= 
        ap_const_lv64_7FFFFFFFFFFFFFFF when (icmp_ln38_reg_379_pp0_iter4_reg(0) = '1') else 
        ap_const_lv64_3FF0000000000000;
    t_fu_160_p3 <= (ap_const_lv1_0 & trunc_ln479_fu_156_p1);
    trunc_ln479_fu_156_p1 <= data_fu_130_p1(63 - 1 downto 0);
    x_3_fu_225_p3 <= 
        x_reg_403 when (icmp_ln54_reg_388(0) = '1') else 
        grp_fu_100_p2;
    xor_ln10_fu_277_p2 <= (xs_sign_fu_235_p3 xor ap_const_lv1_1);
    xor_ln66_fu_305_p2 <= (bitcast_ln66_fu_301_p1 xor ap_const_lv64_8000000000000000);
    xor_ln83_fu_327_p2 <= (bitcast_ln83_fu_323_p1 xor ap_const_lv64_8000000000000000);
    xs_exp_1_fu_243_p4 <= data_1_fu_231_p1(62 downto 52);
    xs_sign_fu_235_p3 <= data_1_fu_231_p1(63 downto 63);
end behav;
