// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Lenet_HW_generic_tanh_double_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        t_in,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [63:0] t_in;
output  [63:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
reg   [63:0] expx_reg_60;
reg   [63:0] expx_reg_60_pp0_iter11_reg;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] grp_fu_130_p2;
reg   [63:0] reg_140;
reg   [0:0] icmp_ln36_reg_380;
reg   [0:0] icmp_ln36_reg_380_pp0_iter19_reg;
reg   [0:0] icmp_ln45_reg_384;
reg   [0:0] icmp_ln45_reg_384_pp0_iter19_reg;
reg   [0:0] and_ln46_reg_388;
reg   [0:0] and_ln46_reg_388_pp0_iter19_reg;
reg   [0:0] tmp_2_reg_392;
reg   [0:0] tmp_2_reg_392_pp0_iter19_reg;
reg   [0:0] icmp_ln54_reg_396;
reg   [0:0] icmp_ln54_reg_396_pp0_iter19_reg;
reg    ap_predicate_pred141_state22;
reg    ap_predicate_pred148_state22;
reg   [0:0] din_sign_reg_366;
reg   [0:0] din_sign_reg_366_pp0_iter1_reg;
reg   [0:0] din_sign_reg_366_pp0_iter2_reg;
reg   [0:0] din_sign_reg_366_pp0_iter3_reg;
reg   [0:0] din_sign_reg_366_pp0_iter4_reg;
reg   [0:0] din_sign_reg_366_pp0_iter5_reg;
reg   [0:0] din_sign_reg_366_pp0_iter6_reg;
reg   [0:0] din_sign_reg_366_pp0_iter7_reg;
reg   [0:0] din_sign_reg_366_pp0_iter8_reg;
reg   [0:0] din_sign_reg_366_pp0_iter9_reg;
reg   [0:0] din_sign_reg_366_pp0_iter10_reg;
reg   [0:0] din_sign_reg_366_pp0_iter11_reg;
reg   [0:0] din_sign_reg_366_pp0_iter12_reg;
reg   [0:0] din_sign_reg_366_pp0_iter13_reg;
reg   [0:0] din_sign_reg_366_pp0_iter14_reg;
reg   [0:0] din_sign_reg_366_pp0_iter15_reg;
reg   [0:0] din_sign_reg_366_pp0_iter16_reg;
reg   [0:0] din_sign_reg_366_pp0_iter17_reg;
reg   [0:0] din_sign_reg_366_pp0_iter18_reg;
reg   [0:0] din_sign_reg_366_pp0_iter19_reg;
reg   [0:0] din_sign_reg_366_pp0_iter20_reg;
reg   [0:0] din_sign_reg_366_pp0_iter21_reg;
reg   [0:0] din_sign_reg_366_pp0_iter22_reg;
wire   [63:0] abst_in_fu_184_p1;
reg   [63:0] abst_in_reg_371;
reg   [63:0] abst_in_reg_371_pp0_iter1_reg;
wire   [0:0] icmp_ln36_fu_193_p2;
reg   [0:0] icmp_ln36_reg_380_pp0_iter1_reg;
reg   [0:0] icmp_ln36_reg_380_pp0_iter2_reg;
reg   [0:0] icmp_ln36_reg_380_pp0_iter3_reg;
reg   [0:0] icmp_ln36_reg_380_pp0_iter4_reg;
reg   [0:0] icmp_ln36_reg_380_pp0_iter5_reg;
reg   [0:0] icmp_ln36_reg_380_pp0_iter6_reg;
reg   [0:0] icmp_ln36_reg_380_pp0_iter7_reg;
reg   [0:0] icmp_ln36_reg_380_pp0_iter8_reg;
reg   [0:0] icmp_ln36_reg_380_pp0_iter9_reg;
reg   [0:0] icmp_ln36_reg_380_pp0_iter10_reg;
reg   [0:0] icmp_ln36_reg_380_pp0_iter11_reg;
reg   [0:0] icmp_ln36_reg_380_pp0_iter12_reg;
reg   [0:0] icmp_ln36_reg_380_pp0_iter13_reg;
reg   [0:0] icmp_ln36_reg_380_pp0_iter14_reg;
reg   [0:0] icmp_ln36_reg_380_pp0_iter15_reg;
reg   [0:0] icmp_ln36_reg_380_pp0_iter16_reg;
reg   [0:0] icmp_ln36_reg_380_pp0_iter17_reg;
reg   [0:0] icmp_ln36_reg_380_pp0_iter18_reg;
reg   [0:0] icmp_ln36_reg_380_pp0_iter20_reg;
reg   [0:0] icmp_ln36_reg_380_pp0_iter21_reg;
reg   [0:0] icmp_ln36_reg_380_pp0_iter22_reg;
wire   [0:0] icmp_ln45_fu_199_p2;
reg   [0:0] icmp_ln45_reg_384_pp0_iter1_reg;
reg   [0:0] icmp_ln45_reg_384_pp0_iter2_reg;
reg   [0:0] icmp_ln45_reg_384_pp0_iter3_reg;
reg   [0:0] icmp_ln45_reg_384_pp0_iter4_reg;
reg   [0:0] icmp_ln45_reg_384_pp0_iter5_reg;
reg   [0:0] icmp_ln45_reg_384_pp0_iter6_reg;
reg   [0:0] icmp_ln45_reg_384_pp0_iter7_reg;
reg   [0:0] icmp_ln45_reg_384_pp0_iter8_reg;
reg   [0:0] icmp_ln45_reg_384_pp0_iter9_reg;
reg   [0:0] icmp_ln45_reg_384_pp0_iter10_reg;
reg   [0:0] icmp_ln45_reg_384_pp0_iter11_reg;
reg   [0:0] icmp_ln45_reg_384_pp0_iter12_reg;
reg   [0:0] icmp_ln45_reg_384_pp0_iter13_reg;
reg   [0:0] icmp_ln45_reg_384_pp0_iter14_reg;
reg   [0:0] icmp_ln45_reg_384_pp0_iter15_reg;
reg   [0:0] icmp_ln45_reg_384_pp0_iter16_reg;
reg   [0:0] icmp_ln45_reg_384_pp0_iter17_reg;
reg   [0:0] icmp_ln45_reg_384_pp0_iter18_reg;
reg   [0:0] icmp_ln45_reg_384_pp0_iter20_reg;
reg   [0:0] icmp_ln45_reg_384_pp0_iter21_reg;
reg   [0:0] icmp_ln45_reg_384_pp0_iter22_reg;
wire   [0:0] and_ln46_fu_217_p2;
reg   [0:0] and_ln46_reg_388_pp0_iter1_reg;
reg   [0:0] and_ln46_reg_388_pp0_iter2_reg;
reg   [0:0] and_ln46_reg_388_pp0_iter3_reg;
reg   [0:0] and_ln46_reg_388_pp0_iter4_reg;
reg   [0:0] and_ln46_reg_388_pp0_iter5_reg;
reg   [0:0] and_ln46_reg_388_pp0_iter6_reg;
reg   [0:0] and_ln46_reg_388_pp0_iter7_reg;
reg   [0:0] and_ln46_reg_388_pp0_iter8_reg;
reg   [0:0] and_ln46_reg_388_pp0_iter9_reg;
reg   [0:0] and_ln46_reg_388_pp0_iter10_reg;
reg   [0:0] and_ln46_reg_388_pp0_iter11_reg;
reg   [0:0] and_ln46_reg_388_pp0_iter12_reg;
reg   [0:0] and_ln46_reg_388_pp0_iter13_reg;
reg   [0:0] and_ln46_reg_388_pp0_iter14_reg;
reg   [0:0] and_ln46_reg_388_pp0_iter15_reg;
reg   [0:0] and_ln46_reg_388_pp0_iter16_reg;
reg   [0:0] and_ln46_reg_388_pp0_iter17_reg;
reg   [0:0] and_ln46_reg_388_pp0_iter18_reg;
reg   [0:0] and_ln46_reg_388_pp0_iter20_reg;
reg   [0:0] and_ln46_reg_388_pp0_iter21_reg;
reg   [0:0] and_ln46_reg_388_pp0_iter22_reg;
wire   [0:0] tmp_2_fu_135_p2;
reg   [0:0] tmp_2_reg_392_pp0_iter1_reg;
reg   [0:0] tmp_2_reg_392_pp0_iter2_reg;
reg   [0:0] tmp_2_reg_392_pp0_iter3_reg;
reg   [0:0] tmp_2_reg_392_pp0_iter4_reg;
reg   [0:0] tmp_2_reg_392_pp0_iter5_reg;
reg   [0:0] tmp_2_reg_392_pp0_iter6_reg;
reg   [0:0] tmp_2_reg_392_pp0_iter7_reg;
reg   [0:0] tmp_2_reg_392_pp0_iter8_reg;
reg   [0:0] tmp_2_reg_392_pp0_iter9_reg;
reg   [0:0] tmp_2_reg_392_pp0_iter10_reg;
reg   [0:0] tmp_2_reg_392_pp0_iter11_reg;
reg   [0:0] tmp_2_reg_392_pp0_iter12_reg;
reg   [0:0] tmp_2_reg_392_pp0_iter13_reg;
reg   [0:0] tmp_2_reg_392_pp0_iter14_reg;
reg   [0:0] tmp_2_reg_392_pp0_iter15_reg;
reg   [0:0] tmp_2_reg_392_pp0_iter16_reg;
reg   [0:0] tmp_2_reg_392_pp0_iter17_reg;
reg   [0:0] tmp_2_reg_392_pp0_iter18_reg;
reg   [0:0] tmp_2_reg_392_pp0_iter20_reg;
reg   [0:0] tmp_2_reg_392_pp0_iter21_reg;
reg   [0:0] tmp_2_reg_392_pp0_iter22_reg;
wire   [0:0] icmp_ln54_fu_223_p2;
reg   [0:0] icmp_ln54_reg_396_pp0_iter1_reg;
reg   [0:0] icmp_ln54_reg_396_pp0_iter2_reg;
reg   [0:0] icmp_ln54_reg_396_pp0_iter3_reg;
reg   [0:0] icmp_ln54_reg_396_pp0_iter4_reg;
reg   [0:0] icmp_ln54_reg_396_pp0_iter5_reg;
reg   [0:0] icmp_ln54_reg_396_pp0_iter6_reg;
reg   [0:0] icmp_ln54_reg_396_pp0_iter7_reg;
reg   [0:0] icmp_ln54_reg_396_pp0_iter8_reg;
reg   [0:0] icmp_ln54_reg_396_pp0_iter9_reg;
reg   [0:0] icmp_ln54_reg_396_pp0_iter10_reg;
reg   [0:0] icmp_ln54_reg_396_pp0_iter11_reg;
reg   [0:0] icmp_ln54_reg_396_pp0_iter12_reg;
reg   [0:0] icmp_ln54_reg_396_pp0_iter13_reg;
reg   [0:0] icmp_ln54_reg_396_pp0_iter14_reg;
reg   [0:0] icmp_ln54_reg_396_pp0_iter15_reg;
reg   [0:0] icmp_ln54_reg_396_pp0_iter16_reg;
reg   [0:0] icmp_ln54_reg_396_pp0_iter17_reg;
reg   [0:0] icmp_ln54_reg_396_pp0_iter18_reg;
reg   [0:0] icmp_ln54_reg_396_pp0_iter20_reg;
reg   [0:0] icmp_ln54_reg_396_pp0_iter21_reg;
reg   [0:0] icmp_ln54_reg_396_pp0_iter22_reg;
wire   [63:0] bitcast_ln55_fu_235_p1;
wire   [0:0] icmp_ln38_fu_240_p2;
reg   [0:0] icmp_ln38_reg_406;
reg   [0:0] icmp_ln38_reg_406_pp0_iter1_reg;
reg   [0:0] icmp_ln38_reg_406_pp0_iter2_reg;
reg   [0:0] icmp_ln38_reg_406_pp0_iter3_reg;
reg   [0:0] icmp_ln38_reg_406_pp0_iter4_reg;
reg   [0:0] icmp_ln38_reg_406_pp0_iter5_reg;
reg   [0:0] icmp_ln38_reg_406_pp0_iter6_reg;
reg   [0:0] icmp_ln38_reg_406_pp0_iter7_reg;
reg   [0:0] icmp_ln38_reg_406_pp0_iter8_reg;
reg   [0:0] icmp_ln38_reg_406_pp0_iter9_reg;
reg   [0:0] icmp_ln38_reg_406_pp0_iter10_reg;
reg   [0:0] icmp_ln38_reg_406_pp0_iter11_reg;
reg   [0:0] icmp_ln38_reg_406_pp0_iter12_reg;
reg   [0:0] icmp_ln38_reg_406_pp0_iter13_reg;
reg   [0:0] icmp_ln38_reg_406_pp0_iter14_reg;
reg   [0:0] icmp_ln38_reg_406_pp0_iter15_reg;
reg   [0:0] icmp_ln38_reg_406_pp0_iter16_reg;
reg   [0:0] icmp_ln38_reg_406_pp0_iter17_reg;
reg   [0:0] icmp_ln38_reg_406_pp0_iter18_reg;
reg   [0:0] icmp_ln38_reg_406_pp0_iter19_reg;
reg   [0:0] icmp_ln38_reg_406_pp0_iter20_reg;
reg   [0:0] icmp_ln38_reg_406_pp0_iter21_reg;
wire   [63:0] x_3_fu_246_p3;
reg   [63:0] x_3_reg_411;
wire   [0:0] and_ln9_1_fu_293_p2;
reg   [0:0] and_ln9_1_reg_418;
reg   [0:0] and_ln9_1_reg_418_pp0_iter2_reg;
reg   [0:0] and_ln9_1_reg_418_pp0_iter3_reg;
reg   [0:0] and_ln9_1_reg_418_pp0_iter4_reg;
reg   [0:0] and_ln9_1_reg_418_pp0_iter5_reg;
reg   [0:0] and_ln9_1_reg_418_pp0_iter6_reg;
reg   [0:0] and_ln9_1_reg_418_pp0_iter7_reg;
wire   [0:0] and_ln10_1_fu_317_p2;
reg   [0:0] and_ln10_1_reg_422;
reg   [0:0] and_ln10_1_reg_422_pp0_iter2_reg;
reg   [0:0] and_ln10_1_reg_422_pp0_iter3_reg;
reg   [0:0] and_ln10_1_reg_422_pp0_iter4_reg;
reg   [0:0] and_ln10_1_reg_422_pp0_iter5_reg;
reg   [0:0] and_ln10_1_reg_422_pp0_iter6_reg;
reg   [0:0] and_ln10_1_reg_422_pp0_iter7_reg;
wire   [63:0] grp_fu_100_p2;
reg   [63:0] add_reg_426;
wire   [63:0] grp_fu_126_p2;
wire   [63:0] grp_exp_generic_double_s_fu_89_ap_return;
reg   [63:0] tmp_4_reg_436;
wire   [63:0] grp_fu_109_p2;
wire   [63:0] grp_fu_114_p2;
reg   [63:0] add2_reg_446;
wire   [63:0] bitcast_ln66_1_fu_333_p1;
wire   [63:0] select_ln38_fu_338_p3;
wire    grp_exp_generic_double_s_fu_89_ap_start;
wire    grp_exp_generic_double_s_fu_89_ap_done;
wire    grp_exp_generic_double_s_fu_89_ap_idle;
wire    grp_exp_generic_double_s_fu_89_ap_ready;
reg    grp_exp_generic_double_s_fu_89_ap_ce;
reg    ap_predicate_op68_call_state3;
wire    ap_block_pp0_stage0_11001_ignoreCallOp68;
wire   [63:0] ap_phi_reg_pp0_iter0_expx_reg_60;
reg   [63:0] ap_phi_reg_pp0_iter1_expx_reg_60;
reg   [63:0] ap_phi_reg_pp0_iter2_expx_reg_60;
reg   [63:0] ap_phi_reg_pp0_iter3_expx_reg_60;
reg   [63:0] ap_phi_reg_pp0_iter4_expx_reg_60;
reg   [63:0] ap_phi_reg_pp0_iter5_expx_reg_60;
reg   [63:0] ap_phi_reg_pp0_iter6_expx_reg_60;
reg   [63:0] ap_phi_reg_pp0_iter7_expx_reg_60;
reg   [63:0] ap_phi_reg_pp0_iter8_expx_reg_60;
reg   [63:0] ap_phi_reg_pp0_iter9_expx_reg_60;
reg   [63:0] ap_phi_reg_pp0_iter10_expx_reg_60;
reg    ap_predicate_pred534_state10;
reg   [63:0] ap_phi_mux_resultf_3_phi_fu_76_p10;
wire   [63:0] ap_phi_reg_pp0_iter0_resultf_3_reg_72;
reg   [63:0] ap_phi_reg_pp0_iter1_resultf_3_reg_72;
reg   [63:0] ap_phi_reg_pp0_iter2_resultf_3_reg_72;
reg   [63:0] ap_phi_reg_pp0_iter3_resultf_3_reg_72;
reg   [63:0] ap_phi_reg_pp0_iter4_resultf_3_reg_72;
reg   [63:0] ap_phi_reg_pp0_iter5_resultf_3_reg_72;
reg   [63:0] ap_phi_reg_pp0_iter6_resultf_3_reg_72;
reg   [63:0] ap_phi_reg_pp0_iter7_resultf_3_reg_72;
reg   [63:0] ap_phi_reg_pp0_iter8_resultf_3_reg_72;
reg   [63:0] ap_phi_reg_pp0_iter9_resultf_3_reg_72;
reg   [63:0] ap_phi_reg_pp0_iter10_resultf_3_reg_72;
reg   [63:0] ap_phi_reg_pp0_iter11_resultf_3_reg_72;
reg   [63:0] ap_phi_reg_pp0_iter12_resultf_3_reg_72;
reg   [63:0] ap_phi_reg_pp0_iter13_resultf_3_reg_72;
reg   [63:0] ap_phi_reg_pp0_iter14_resultf_3_reg_72;
reg   [63:0] ap_phi_reg_pp0_iter15_resultf_3_reg_72;
reg   [63:0] ap_phi_reg_pp0_iter16_resultf_3_reg_72;
reg   [63:0] ap_phi_reg_pp0_iter17_resultf_3_reg_72;
reg   [63:0] ap_phi_reg_pp0_iter18_resultf_3_reg_72;
reg   [63:0] ap_phi_reg_pp0_iter19_resultf_3_reg_72;
reg   [63:0] ap_phi_reg_pp0_iter20_resultf_3_reg_72;
reg   [63:0] ap_phi_reg_pp0_iter21_resultf_3_reg_72;
reg   [63:0] ap_phi_reg_pp0_iter22_resultf_3_reg_72;
reg   [63:0] ap_phi_reg_pp0_iter23_resultf_3_reg_72;
wire   [63:0] grp_fu_120_p2;
reg    grp_exp_generic_double_s_fu_89_ap_start_reg;
reg    ap_predicate_op68_call_state3_state2;
wire    ap_block_pp0_stage0;
reg   [63:0] grp_fu_100_p0;
reg   [63:0] grp_fu_100_p1;
reg   [63:0] grp_fu_130_p0;
reg    ap_predicate_pred747_state13;
reg    ap_predicate_pred752_state13;
wire   [63:0] data_fu_146_p1;
wire   [62:0] trunc_ln479_fu_172_p1;
wire   [63:0] t_fu_176_p3;
wire   [10:0] din_exp_fu_158_p4;
wire   [51:0] din_sig_fu_168_p1;
wire   [0:0] icmp_ln46_fu_205_p2;
wire   [0:0] icmp_ln46_1_fu_211_p2;
wire   [63:0] or_ln55_fu_229_p2;
wire   [63:0] grp_fu_104_p2;
wire   [63:0] data_1_fu_253_p1;
wire   [10:0] xs_exp_1_fu_265_p4;
wire   [0:0] icmp_ln9_fu_275_p2;
wire   [0:0] icmp_ln9_1_fu_281_p2;
wire   [0:0] and_ln9_fu_287_p2;
wire   [0:0] xs_sign_fu_257_p3;
wire   [0:0] xor_ln10_fu_299_p2;
wire   [0:0] and_ln10_fu_311_p2;
wire   [0:0] icmp_ln10_fu_305_p2;
wire   [63:0] bitcast_ln66_fu_323_p1;
wire   [63:0] xor_ln66_fu_327_p2;
wire   [63:0] bitcast_ln83_fu_345_p1;
wire   [63:0] xor_ln83_fu_349_p2;
wire   [63:0] bitcast_ln83_1_fu_355_p1;
reg   [1:0] grp_fu_100_opcode;
wire    ap_block_pp0_stage0_00001;
reg    grp_fu_100_ce;
reg    grp_fu_104_ce;
reg    grp_fu_109_ce;
reg    grp_fu_114_ce;
reg    grp_fu_120_ce;
reg    grp_fu_126_ce;
reg    grp_fu_130_ce;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to22;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_523;
reg    ap_condition_653;
reg    ap_condition_490;
reg    ap_condition_120;
reg    ap_condition_612;
reg    ap_condition_617;
reg    ap_condition_499;
reg    ap_condition_719;
reg    ap_condition_713;
reg    ap_condition_871;
reg    ap_condition_711;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 grp_exp_generic_double_s_fu_89_ap_start_reg = 1'b0;
end

Lenet_HW_exp_generic_double_s grp_exp_generic_double_s_fu_89(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_exp_generic_double_s_fu_89_ap_start),
    .ap_done(grp_exp_generic_double_s_fu_89_ap_done),
    .ap_idle(grp_exp_generic_double_s_fu_89_ap_idle),
    .ap_ready(grp_exp_generic_double_s_fu_89_ap_ready),
    .ap_ce(grp_exp_generic_double_s_fu_89_ap_ce),
    .x(x_3_reg_411),
    .ap_return(grp_exp_generic_double_s_fu_89_ap_return)
);

Lenet_HW_dadddsub_64ns_64ns_64_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadddsub_64ns_64ns_64_2_full_dsp_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_100_p0),
    .din1(grp_fu_100_p1),
    .opcode(grp_fu_100_opcode),
    .ce(grp_fu_100_ce),
    .dout(grp_fu_100_p2)
);

Lenet_HW_dadd_64ns_64ns_64_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_2_full_dsp_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(abst_in_fu_184_p1),
    .din1(abst_in_fu_184_p1),
    .ce(grp_fu_104_ce),
    .dout(grp_fu_104_p2)
);

Lenet_HW_dadd_64ns_64ns_64_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_2_full_dsp_1_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_4_reg_436),
    .din1(64'd13830554455654793216),
    .ce(grp_fu_109_ce),
    .dout(grp_fu_109_p2)
);

Lenet_HW_dadd_64ns_64ns_64_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_2_full_dsp_1_U18(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_phi_reg_pp0_iter10_expx_reg_60),
    .din1(64'd4611686018427387904),
    .ce(grp_fu_114_ce),
    .dout(grp_fu_114_p2)
);

Lenet_HW_dsub_64ns_64ns_64_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dsub_64ns_64ns_64_2_full_dsp_1_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(64'd4607182418800017408),
    .din1(reg_140),
    .ce(grp_fu_120_ce),
    .dout(grp_fu_120_p2)
);

Lenet_HW_dmul_64ns_64ns_64_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_2_max_dsp_1_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(abst_in_reg_371_pp0_iter1_reg),
    .din1(add_reg_426),
    .ce(grp_fu_126_ce),
    .dout(grp_fu_126_p2)
);

Lenet_HW_ddiv_64ns_64ns_64_10_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 10 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
ddiv_64ns_64ns_64_10_no_dsp_1_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_130_p0),
    .din1(add2_reg_446),
    .ce(grp_fu_130_ce),
    .dout(grp_fu_130_p2)
);

Lenet_HW_dcmp_64ns_64ns_1_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
dcmp_64ns_64ns_1_1_no_dsp_1_U22(
    .din0(abst_in_fu_184_p1),
    .din1(64'd4626885667169763328),
    .opcode(5'd4),
    .dout(tmp_2_fu_135_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_exp_generic_double_s_fu_89_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_predicate_op68_call_state3_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            grp_exp_generic_double_s_fu_89_ap_start_reg <= 1'b1;
        end else if ((grp_exp_generic_double_s_fu_89_ap_ready == 1'b1)) begin
            grp_exp_generic_double_s_fu_89_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_523)) begin
        if ((ap_predicate_pred534_state10 == 1'b1)) begin
            ap_phi_reg_pp0_iter10_expx_reg_60 <= grp_fu_109_p2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter10_expx_reg_60 <= ap_phi_reg_pp0_iter9_expx_reg_60;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_490)) begin
        if ((1'b1 == ap_condition_653)) begin
            ap_phi_reg_pp0_iter1_resultf_3_reg_72 <= 64'd4607182418800017408;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_resultf_3_reg_72 <= ap_phi_reg_pp0_iter0_resultf_3_reg_72;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_120)) begin
        if ((ap_predicate_pred148_state22 == 1'b1)) begin
            ap_phi_reg_pp0_iter22_resultf_3_reg_72 <= grp_fu_130_p2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter22_resultf_3_reg_72 <= ap_phi_reg_pp0_iter21_resultf_3_reg_72;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_612)) begin
        if ((icmp_ln36_reg_380_pp0_iter21_reg == 1'd1)) begin
            ap_phi_reg_pp0_iter23_resultf_3_reg_72 <= select_ln38_fu_338_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter23_resultf_3_reg_72 <= ap_phi_reg_pp0_iter22_resultf_3_reg_72;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_2_reg_392_pp0_iter1_reg == 1'd1) & (icmp_ln45_reg_384_pp0_iter1_reg == 1'd0) & (1'b1 == ap_ce) & (icmp_ln36_reg_380_pp0_iter1_reg == 1'd0) & (1'd1 == and_ln10_1_reg_422) & (1'd0 == and_ln9_1_reg_418) & (1'd0 == and_ln46_reg_388_pp0_iter1_reg) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_2_reg_392_pp0_iter1_reg == 1'd1) & (icmp_ln45_reg_384_pp0_iter1_reg == 1'd0) & (1'b1 == ap_ce) & (icmp_ln36_reg_380_pp0_iter1_reg == 1'd0) & (1'd1 == and_ln9_1_reg_418) & (1'd0 == and_ln46_reg_388_pp0_iter1_reg) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        ap_phi_reg_pp0_iter3_expx_reg_60 <= x_3_reg_411;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter3_expx_reg_60 <= ap_phi_reg_pp0_iter2_expx_reg_60;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_499)) begin
        if ((1'b1 == ap_condition_617)) begin
            ap_phi_reg_pp0_iter4_resultf_3_reg_72 <= grp_fu_126_p2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_resultf_3_reg_72 <= ap_phi_reg_pp0_iter3_resultf_3_reg_72;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        abst_in_reg_371[62 : 0] <= abst_in_fu_184_p1[62 : 0];
        abst_in_reg_371_pp0_iter1_reg[62 : 0] <= abst_in_reg_371[62 : 0];
        and_ln10_1_reg_422 <= and_ln10_1_fu_317_p2;
        and_ln46_reg_388 <= and_ln46_fu_217_p2;
        and_ln46_reg_388_pp0_iter1_reg <= and_ln46_reg_388;
        and_ln9_1_reg_418 <= and_ln9_1_fu_293_p2;
        din_sign_reg_366 <= data_fu_146_p1[32'd63];
        din_sign_reg_366_pp0_iter1_reg <= din_sign_reg_366;
        icmp_ln36_reg_380 <= icmp_ln36_fu_193_p2;
        icmp_ln36_reg_380_pp0_iter1_reg <= icmp_ln36_reg_380;
        icmp_ln38_reg_406 <= icmp_ln38_fu_240_p2;
        icmp_ln38_reg_406_pp0_iter1_reg <= icmp_ln38_reg_406;
        icmp_ln45_reg_384 <= icmp_ln45_fu_199_p2;
        icmp_ln45_reg_384_pp0_iter1_reg <= icmp_ln45_reg_384;
        icmp_ln54_reg_396 <= icmp_ln54_fu_223_p2;
        icmp_ln54_reg_396_pp0_iter1_reg <= icmp_ln54_reg_396;
        tmp_2_reg_392 <= tmp_2_fu_135_p2;
        tmp_2_reg_392_pp0_iter1_reg <= tmp_2_reg_392;
        x_3_reg_411 <= x_3_fu_246_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add2_reg_446 <= grp_fu_114_p2;
        and_ln10_1_reg_422_pp0_iter2_reg <= and_ln10_1_reg_422;
        and_ln10_1_reg_422_pp0_iter3_reg <= and_ln10_1_reg_422_pp0_iter2_reg;
        and_ln10_1_reg_422_pp0_iter4_reg <= and_ln10_1_reg_422_pp0_iter3_reg;
        and_ln10_1_reg_422_pp0_iter5_reg <= and_ln10_1_reg_422_pp0_iter4_reg;
        and_ln10_1_reg_422_pp0_iter6_reg <= and_ln10_1_reg_422_pp0_iter5_reg;
        and_ln10_1_reg_422_pp0_iter7_reg <= and_ln10_1_reg_422_pp0_iter6_reg;
        and_ln46_reg_388_pp0_iter10_reg <= and_ln46_reg_388_pp0_iter9_reg;
        and_ln46_reg_388_pp0_iter11_reg <= and_ln46_reg_388_pp0_iter10_reg;
        and_ln46_reg_388_pp0_iter12_reg <= and_ln46_reg_388_pp0_iter11_reg;
        and_ln46_reg_388_pp0_iter13_reg <= and_ln46_reg_388_pp0_iter12_reg;
        and_ln46_reg_388_pp0_iter14_reg <= and_ln46_reg_388_pp0_iter13_reg;
        and_ln46_reg_388_pp0_iter15_reg <= and_ln46_reg_388_pp0_iter14_reg;
        and_ln46_reg_388_pp0_iter16_reg <= and_ln46_reg_388_pp0_iter15_reg;
        and_ln46_reg_388_pp0_iter17_reg <= and_ln46_reg_388_pp0_iter16_reg;
        and_ln46_reg_388_pp0_iter18_reg <= and_ln46_reg_388_pp0_iter17_reg;
        and_ln46_reg_388_pp0_iter19_reg <= and_ln46_reg_388_pp0_iter18_reg;
        and_ln46_reg_388_pp0_iter20_reg <= and_ln46_reg_388_pp0_iter19_reg;
        and_ln46_reg_388_pp0_iter21_reg <= and_ln46_reg_388_pp0_iter20_reg;
        and_ln46_reg_388_pp0_iter22_reg <= and_ln46_reg_388_pp0_iter21_reg;
        and_ln46_reg_388_pp0_iter2_reg <= and_ln46_reg_388_pp0_iter1_reg;
        and_ln46_reg_388_pp0_iter3_reg <= and_ln46_reg_388_pp0_iter2_reg;
        and_ln46_reg_388_pp0_iter4_reg <= and_ln46_reg_388_pp0_iter3_reg;
        and_ln46_reg_388_pp0_iter5_reg <= and_ln46_reg_388_pp0_iter4_reg;
        and_ln46_reg_388_pp0_iter6_reg <= and_ln46_reg_388_pp0_iter5_reg;
        and_ln46_reg_388_pp0_iter7_reg <= and_ln46_reg_388_pp0_iter6_reg;
        and_ln46_reg_388_pp0_iter8_reg <= and_ln46_reg_388_pp0_iter7_reg;
        and_ln46_reg_388_pp0_iter9_reg <= and_ln46_reg_388_pp0_iter8_reg;
        and_ln9_1_reg_418_pp0_iter2_reg <= and_ln9_1_reg_418;
        and_ln9_1_reg_418_pp0_iter3_reg <= and_ln9_1_reg_418_pp0_iter2_reg;
        and_ln9_1_reg_418_pp0_iter4_reg <= and_ln9_1_reg_418_pp0_iter3_reg;
        and_ln9_1_reg_418_pp0_iter5_reg <= and_ln9_1_reg_418_pp0_iter4_reg;
        and_ln9_1_reg_418_pp0_iter6_reg <= and_ln9_1_reg_418_pp0_iter5_reg;
        and_ln9_1_reg_418_pp0_iter7_reg <= and_ln9_1_reg_418_pp0_iter6_reg;
        ap_predicate_pred141_state22 <= ((icmp_ln54_reg_396_pp0_iter19_reg == 1'd0) & (tmp_2_reg_392_pp0_iter19_reg == 1'd1) & (icmp_ln45_reg_384_pp0_iter19_reg == 1'd0) & (1'd0 == and_ln46_reg_388_pp0_iter19_reg) & (icmp_ln36_reg_380_pp0_iter19_reg == 1'd0));
        ap_predicate_pred148_state22 <= ((icmp_ln54_reg_396_pp0_iter19_reg == 1'd1) & (tmp_2_reg_392_pp0_iter19_reg == 1'd1) & (icmp_ln45_reg_384_pp0_iter19_reg == 1'd0) & (1'd0 == and_ln46_reg_388_pp0_iter19_reg) & (icmp_ln36_reg_380_pp0_iter19_reg == 1'd0));
        ap_predicate_pred534_state10 <= ((tmp_2_reg_392_pp0_iter7_reg == 1'd1) & (icmp_ln45_reg_384_pp0_iter7_reg == 1'd0) & (icmp_ln36_reg_380_pp0_iter7_reg == 1'd0) & (1'd0 == and_ln10_1_reg_422_pp0_iter7_reg) & (1'd0 == and_ln9_1_reg_418_pp0_iter7_reg) & (1'd0 == and_ln46_reg_388_pp0_iter7_reg));
        ap_predicate_pred747_state13 <= ((icmp_ln54_reg_396_pp0_iter10_reg == 1'd0) & (tmp_2_reg_392_pp0_iter10_reg == 1'd1) & (icmp_ln45_reg_384_pp0_iter10_reg == 1'd0) & (icmp_ln36_reg_380_pp0_iter10_reg == 1'd0) & (1'd0 == and_ln46_reg_388_pp0_iter10_reg));
        ap_predicate_pred752_state13 <= ((icmp_ln54_reg_396_pp0_iter10_reg == 1'd1) & (tmp_2_reg_392_pp0_iter10_reg == 1'd1) & (icmp_ln45_reg_384_pp0_iter10_reg == 1'd0) & (icmp_ln36_reg_380_pp0_iter10_reg == 1'd0) & (1'd0 == and_ln46_reg_388_pp0_iter10_reg));
        din_sign_reg_366_pp0_iter10_reg <= din_sign_reg_366_pp0_iter9_reg;
        din_sign_reg_366_pp0_iter11_reg <= din_sign_reg_366_pp0_iter10_reg;
        din_sign_reg_366_pp0_iter12_reg <= din_sign_reg_366_pp0_iter11_reg;
        din_sign_reg_366_pp0_iter13_reg <= din_sign_reg_366_pp0_iter12_reg;
        din_sign_reg_366_pp0_iter14_reg <= din_sign_reg_366_pp0_iter13_reg;
        din_sign_reg_366_pp0_iter15_reg <= din_sign_reg_366_pp0_iter14_reg;
        din_sign_reg_366_pp0_iter16_reg <= din_sign_reg_366_pp0_iter15_reg;
        din_sign_reg_366_pp0_iter17_reg <= din_sign_reg_366_pp0_iter16_reg;
        din_sign_reg_366_pp0_iter18_reg <= din_sign_reg_366_pp0_iter17_reg;
        din_sign_reg_366_pp0_iter19_reg <= din_sign_reg_366_pp0_iter18_reg;
        din_sign_reg_366_pp0_iter20_reg <= din_sign_reg_366_pp0_iter19_reg;
        din_sign_reg_366_pp0_iter21_reg <= din_sign_reg_366_pp0_iter20_reg;
        din_sign_reg_366_pp0_iter22_reg <= din_sign_reg_366_pp0_iter21_reg;
        din_sign_reg_366_pp0_iter2_reg <= din_sign_reg_366_pp0_iter1_reg;
        din_sign_reg_366_pp0_iter3_reg <= din_sign_reg_366_pp0_iter2_reg;
        din_sign_reg_366_pp0_iter4_reg <= din_sign_reg_366_pp0_iter3_reg;
        din_sign_reg_366_pp0_iter5_reg <= din_sign_reg_366_pp0_iter4_reg;
        din_sign_reg_366_pp0_iter6_reg <= din_sign_reg_366_pp0_iter5_reg;
        din_sign_reg_366_pp0_iter7_reg <= din_sign_reg_366_pp0_iter6_reg;
        din_sign_reg_366_pp0_iter8_reg <= din_sign_reg_366_pp0_iter7_reg;
        din_sign_reg_366_pp0_iter9_reg <= din_sign_reg_366_pp0_iter8_reg;
        expx_reg_60_pp0_iter11_reg <= expx_reg_60;
        icmp_ln36_reg_380_pp0_iter10_reg <= icmp_ln36_reg_380_pp0_iter9_reg;
        icmp_ln36_reg_380_pp0_iter11_reg <= icmp_ln36_reg_380_pp0_iter10_reg;
        icmp_ln36_reg_380_pp0_iter12_reg <= icmp_ln36_reg_380_pp0_iter11_reg;
        icmp_ln36_reg_380_pp0_iter13_reg <= icmp_ln36_reg_380_pp0_iter12_reg;
        icmp_ln36_reg_380_pp0_iter14_reg <= icmp_ln36_reg_380_pp0_iter13_reg;
        icmp_ln36_reg_380_pp0_iter15_reg <= icmp_ln36_reg_380_pp0_iter14_reg;
        icmp_ln36_reg_380_pp0_iter16_reg <= icmp_ln36_reg_380_pp0_iter15_reg;
        icmp_ln36_reg_380_pp0_iter17_reg <= icmp_ln36_reg_380_pp0_iter16_reg;
        icmp_ln36_reg_380_pp0_iter18_reg <= icmp_ln36_reg_380_pp0_iter17_reg;
        icmp_ln36_reg_380_pp0_iter19_reg <= icmp_ln36_reg_380_pp0_iter18_reg;
        icmp_ln36_reg_380_pp0_iter20_reg <= icmp_ln36_reg_380_pp0_iter19_reg;
        icmp_ln36_reg_380_pp0_iter21_reg <= icmp_ln36_reg_380_pp0_iter20_reg;
        icmp_ln36_reg_380_pp0_iter22_reg <= icmp_ln36_reg_380_pp0_iter21_reg;
        icmp_ln36_reg_380_pp0_iter2_reg <= icmp_ln36_reg_380_pp0_iter1_reg;
        icmp_ln36_reg_380_pp0_iter3_reg <= icmp_ln36_reg_380_pp0_iter2_reg;
        icmp_ln36_reg_380_pp0_iter4_reg <= icmp_ln36_reg_380_pp0_iter3_reg;
        icmp_ln36_reg_380_pp0_iter5_reg <= icmp_ln36_reg_380_pp0_iter4_reg;
        icmp_ln36_reg_380_pp0_iter6_reg <= icmp_ln36_reg_380_pp0_iter5_reg;
        icmp_ln36_reg_380_pp0_iter7_reg <= icmp_ln36_reg_380_pp0_iter6_reg;
        icmp_ln36_reg_380_pp0_iter8_reg <= icmp_ln36_reg_380_pp0_iter7_reg;
        icmp_ln36_reg_380_pp0_iter9_reg <= icmp_ln36_reg_380_pp0_iter8_reg;
        icmp_ln38_reg_406_pp0_iter10_reg <= icmp_ln38_reg_406_pp0_iter9_reg;
        icmp_ln38_reg_406_pp0_iter11_reg <= icmp_ln38_reg_406_pp0_iter10_reg;
        icmp_ln38_reg_406_pp0_iter12_reg <= icmp_ln38_reg_406_pp0_iter11_reg;
        icmp_ln38_reg_406_pp0_iter13_reg <= icmp_ln38_reg_406_pp0_iter12_reg;
        icmp_ln38_reg_406_pp0_iter14_reg <= icmp_ln38_reg_406_pp0_iter13_reg;
        icmp_ln38_reg_406_pp0_iter15_reg <= icmp_ln38_reg_406_pp0_iter14_reg;
        icmp_ln38_reg_406_pp0_iter16_reg <= icmp_ln38_reg_406_pp0_iter15_reg;
        icmp_ln38_reg_406_pp0_iter17_reg <= icmp_ln38_reg_406_pp0_iter16_reg;
        icmp_ln38_reg_406_pp0_iter18_reg <= icmp_ln38_reg_406_pp0_iter17_reg;
        icmp_ln38_reg_406_pp0_iter19_reg <= icmp_ln38_reg_406_pp0_iter18_reg;
        icmp_ln38_reg_406_pp0_iter20_reg <= icmp_ln38_reg_406_pp0_iter19_reg;
        icmp_ln38_reg_406_pp0_iter21_reg <= icmp_ln38_reg_406_pp0_iter20_reg;
        icmp_ln38_reg_406_pp0_iter2_reg <= icmp_ln38_reg_406_pp0_iter1_reg;
        icmp_ln38_reg_406_pp0_iter3_reg <= icmp_ln38_reg_406_pp0_iter2_reg;
        icmp_ln38_reg_406_pp0_iter4_reg <= icmp_ln38_reg_406_pp0_iter3_reg;
        icmp_ln38_reg_406_pp0_iter5_reg <= icmp_ln38_reg_406_pp0_iter4_reg;
        icmp_ln38_reg_406_pp0_iter6_reg <= icmp_ln38_reg_406_pp0_iter5_reg;
        icmp_ln38_reg_406_pp0_iter7_reg <= icmp_ln38_reg_406_pp0_iter6_reg;
        icmp_ln38_reg_406_pp0_iter8_reg <= icmp_ln38_reg_406_pp0_iter7_reg;
        icmp_ln38_reg_406_pp0_iter9_reg <= icmp_ln38_reg_406_pp0_iter8_reg;
        icmp_ln45_reg_384_pp0_iter10_reg <= icmp_ln45_reg_384_pp0_iter9_reg;
        icmp_ln45_reg_384_pp0_iter11_reg <= icmp_ln45_reg_384_pp0_iter10_reg;
        icmp_ln45_reg_384_pp0_iter12_reg <= icmp_ln45_reg_384_pp0_iter11_reg;
        icmp_ln45_reg_384_pp0_iter13_reg <= icmp_ln45_reg_384_pp0_iter12_reg;
        icmp_ln45_reg_384_pp0_iter14_reg <= icmp_ln45_reg_384_pp0_iter13_reg;
        icmp_ln45_reg_384_pp0_iter15_reg <= icmp_ln45_reg_384_pp0_iter14_reg;
        icmp_ln45_reg_384_pp0_iter16_reg <= icmp_ln45_reg_384_pp0_iter15_reg;
        icmp_ln45_reg_384_pp0_iter17_reg <= icmp_ln45_reg_384_pp0_iter16_reg;
        icmp_ln45_reg_384_pp0_iter18_reg <= icmp_ln45_reg_384_pp0_iter17_reg;
        icmp_ln45_reg_384_pp0_iter19_reg <= icmp_ln45_reg_384_pp0_iter18_reg;
        icmp_ln45_reg_384_pp0_iter20_reg <= icmp_ln45_reg_384_pp0_iter19_reg;
        icmp_ln45_reg_384_pp0_iter21_reg <= icmp_ln45_reg_384_pp0_iter20_reg;
        icmp_ln45_reg_384_pp0_iter22_reg <= icmp_ln45_reg_384_pp0_iter21_reg;
        icmp_ln45_reg_384_pp0_iter2_reg <= icmp_ln45_reg_384_pp0_iter1_reg;
        icmp_ln45_reg_384_pp0_iter3_reg <= icmp_ln45_reg_384_pp0_iter2_reg;
        icmp_ln45_reg_384_pp0_iter4_reg <= icmp_ln45_reg_384_pp0_iter3_reg;
        icmp_ln45_reg_384_pp0_iter5_reg <= icmp_ln45_reg_384_pp0_iter4_reg;
        icmp_ln45_reg_384_pp0_iter6_reg <= icmp_ln45_reg_384_pp0_iter5_reg;
        icmp_ln45_reg_384_pp0_iter7_reg <= icmp_ln45_reg_384_pp0_iter6_reg;
        icmp_ln45_reg_384_pp0_iter8_reg <= icmp_ln45_reg_384_pp0_iter7_reg;
        icmp_ln45_reg_384_pp0_iter9_reg <= icmp_ln45_reg_384_pp0_iter8_reg;
        icmp_ln54_reg_396_pp0_iter10_reg <= icmp_ln54_reg_396_pp0_iter9_reg;
        icmp_ln54_reg_396_pp0_iter11_reg <= icmp_ln54_reg_396_pp0_iter10_reg;
        icmp_ln54_reg_396_pp0_iter12_reg <= icmp_ln54_reg_396_pp0_iter11_reg;
        icmp_ln54_reg_396_pp0_iter13_reg <= icmp_ln54_reg_396_pp0_iter12_reg;
        icmp_ln54_reg_396_pp0_iter14_reg <= icmp_ln54_reg_396_pp0_iter13_reg;
        icmp_ln54_reg_396_pp0_iter15_reg <= icmp_ln54_reg_396_pp0_iter14_reg;
        icmp_ln54_reg_396_pp0_iter16_reg <= icmp_ln54_reg_396_pp0_iter15_reg;
        icmp_ln54_reg_396_pp0_iter17_reg <= icmp_ln54_reg_396_pp0_iter16_reg;
        icmp_ln54_reg_396_pp0_iter18_reg <= icmp_ln54_reg_396_pp0_iter17_reg;
        icmp_ln54_reg_396_pp0_iter19_reg <= icmp_ln54_reg_396_pp0_iter18_reg;
        icmp_ln54_reg_396_pp0_iter20_reg <= icmp_ln54_reg_396_pp0_iter19_reg;
        icmp_ln54_reg_396_pp0_iter21_reg <= icmp_ln54_reg_396_pp0_iter20_reg;
        icmp_ln54_reg_396_pp0_iter22_reg <= icmp_ln54_reg_396_pp0_iter21_reg;
        icmp_ln54_reg_396_pp0_iter2_reg <= icmp_ln54_reg_396_pp0_iter1_reg;
        icmp_ln54_reg_396_pp0_iter3_reg <= icmp_ln54_reg_396_pp0_iter2_reg;
        icmp_ln54_reg_396_pp0_iter4_reg <= icmp_ln54_reg_396_pp0_iter3_reg;
        icmp_ln54_reg_396_pp0_iter5_reg <= icmp_ln54_reg_396_pp0_iter4_reg;
        icmp_ln54_reg_396_pp0_iter6_reg <= icmp_ln54_reg_396_pp0_iter5_reg;
        icmp_ln54_reg_396_pp0_iter7_reg <= icmp_ln54_reg_396_pp0_iter6_reg;
        icmp_ln54_reg_396_pp0_iter8_reg <= icmp_ln54_reg_396_pp0_iter7_reg;
        icmp_ln54_reg_396_pp0_iter9_reg <= icmp_ln54_reg_396_pp0_iter8_reg;
        tmp_2_reg_392_pp0_iter10_reg <= tmp_2_reg_392_pp0_iter9_reg;
        tmp_2_reg_392_pp0_iter11_reg <= tmp_2_reg_392_pp0_iter10_reg;
        tmp_2_reg_392_pp0_iter12_reg <= tmp_2_reg_392_pp0_iter11_reg;
        tmp_2_reg_392_pp0_iter13_reg <= tmp_2_reg_392_pp0_iter12_reg;
        tmp_2_reg_392_pp0_iter14_reg <= tmp_2_reg_392_pp0_iter13_reg;
        tmp_2_reg_392_pp0_iter15_reg <= tmp_2_reg_392_pp0_iter14_reg;
        tmp_2_reg_392_pp0_iter16_reg <= tmp_2_reg_392_pp0_iter15_reg;
        tmp_2_reg_392_pp0_iter17_reg <= tmp_2_reg_392_pp0_iter16_reg;
        tmp_2_reg_392_pp0_iter18_reg <= tmp_2_reg_392_pp0_iter17_reg;
        tmp_2_reg_392_pp0_iter19_reg <= tmp_2_reg_392_pp0_iter18_reg;
        tmp_2_reg_392_pp0_iter20_reg <= tmp_2_reg_392_pp0_iter19_reg;
        tmp_2_reg_392_pp0_iter21_reg <= tmp_2_reg_392_pp0_iter20_reg;
        tmp_2_reg_392_pp0_iter22_reg <= tmp_2_reg_392_pp0_iter21_reg;
        tmp_2_reg_392_pp0_iter2_reg <= tmp_2_reg_392_pp0_iter1_reg;
        tmp_2_reg_392_pp0_iter3_reg <= tmp_2_reg_392_pp0_iter2_reg;
        tmp_2_reg_392_pp0_iter4_reg <= tmp_2_reg_392_pp0_iter3_reg;
        tmp_2_reg_392_pp0_iter5_reg <= tmp_2_reg_392_pp0_iter4_reg;
        tmp_2_reg_392_pp0_iter6_reg <= tmp_2_reg_392_pp0_iter5_reg;
        tmp_2_reg_392_pp0_iter7_reg <= tmp_2_reg_392_pp0_iter6_reg;
        tmp_2_reg_392_pp0_iter8_reg <= tmp_2_reg_392_pp0_iter7_reg;
        tmp_2_reg_392_pp0_iter9_reg <= tmp_2_reg_392_pp0_iter8_reg;
        tmp_4_reg_436 <= grp_exp_generic_double_s_fu_89_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_reg_426 <= grp_fu_100_p2;
        ap_phi_reg_pp0_iter2_expx_reg_60 <= ap_phi_reg_pp0_iter1_expx_reg_60;
        ap_phi_reg_pp0_iter2_resultf_3_reg_72 <= ap_phi_reg_pp0_iter1_resultf_3_reg_72;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter10_resultf_3_reg_72 <= ap_phi_reg_pp0_iter9_resultf_3_reg_72;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter11_resultf_3_reg_72 <= ap_phi_reg_pp0_iter10_resultf_3_reg_72;
        expx_reg_60 <= ap_phi_reg_pp0_iter10_expx_reg_60;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter12_resultf_3_reg_72 <= ap_phi_reg_pp0_iter11_resultf_3_reg_72;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter13_resultf_3_reg_72 <= ap_phi_reg_pp0_iter12_resultf_3_reg_72;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter14_resultf_3_reg_72 <= ap_phi_reg_pp0_iter13_resultf_3_reg_72;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter15_resultf_3_reg_72 <= ap_phi_reg_pp0_iter14_resultf_3_reg_72;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter16_resultf_3_reg_72 <= ap_phi_reg_pp0_iter15_resultf_3_reg_72;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter17_resultf_3_reg_72 <= ap_phi_reg_pp0_iter16_resultf_3_reg_72;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter18_resultf_3_reg_72 <= ap_phi_reg_pp0_iter17_resultf_3_reg_72;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter19_resultf_3_reg_72 <= ap_phi_reg_pp0_iter18_resultf_3_reg_72;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter1_expx_reg_60 <= ap_phi_reg_pp0_iter0_expx_reg_60;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter20_resultf_3_reg_72 <= ap_phi_reg_pp0_iter19_resultf_3_reg_72;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter21_resultf_3_reg_72 <= ap_phi_reg_pp0_iter20_resultf_3_reg_72;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter3_resultf_3_reg_72 <= ap_phi_reg_pp0_iter2_resultf_3_reg_72;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter4_expx_reg_60 <= ap_phi_reg_pp0_iter3_expx_reg_60;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter5_expx_reg_60 <= ap_phi_reg_pp0_iter4_expx_reg_60;
        ap_phi_reg_pp0_iter5_resultf_3_reg_72 <= ap_phi_reg_pp0_iter4_resultf_3_reg_72;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter6_expx_reg_60 <= ap_phi_reg_pp0_iter5_expx_reg_60;
        ap_phi_reg_pp0_iter6_resultf_3_reg_72 <= ap_phi_reg_pp0_iter5_resultf_3_reg_72;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter7_expx_reg_60 <= ap_phi_reg_pp0_iter6_expx_reg_60;
        ap_phi_reg_pp0_iter7_resultf_3_reg_72 <= ap_phi_reg_pp0_iter6_resultf_3_reg_72;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter8_expx_reg_60 <= ap_phi_reg_pp0_iter7_expx_reg_60;
        ap_phi_reg_pp0_iter8_resultf_3_reg_72 <= ap_phi_reg_pp0_iter7_resultf_3_reg_72;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter9_expx_reg_60 <= ap_phi_reg_pp0_iter8_expx_reg_60;
        ap_phi_reg_pp0_iter9_resultf_3_reg_72 <= ap_phi_reg_pp0_iter8_resultf_3_reg_72;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b1 == ap_ce) & (ap_predicate_pred148_state22 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b1 == ap_ce) & (ap_predicate_pred141_state22 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        reg_140 <= grp_fu_130_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter23 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to22 = 1'b1;
    end else begin
        ap_idle_pp0_0to22 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln54_reg_396_pp0_iter22_reg == 1'd0) & (tmp_2_reg_392_pp0_iter22_reg == 1'd1) & (icmp_ln45_reg_384_pp0_iter22_reg == 1'd0) & (icmp_ln36_reg_380_pp0_iter22_reg == 1'd0) & (1'd0 == and_ln46_reg_388_pp0_iter22_reg))) begin
        ap_phi_mux_resultf_3_phi_fu_76_p10 = grp_fu_120_p2;
    end else begin
        ap_phi_mux_resultf_3_phi_fu_76_p10 = ap_phi_reg_pp0_iter23_resultf_3_reg_72;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to22 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp68))) begin
        grp_exp_generic_double_s_fu_89_ap_ce = 1'b1;
    end else begin
        grp_exp_generic_double_s_fu_89_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_100_ce = 1'b1;
    end else begin
        grp_fu_100_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_871)) begin
        if ((1'b1 == ap_condition_713)) begin
            grp_fu_100_opcode = 2'd1;
        end else if ((1'b1 == ap_condition_719)) begin
            grp_fu_100_opcode = 2'd0;
        end else begin
            grp_fu_100_opcode = 'bx;
        end
    end else begin
        grp_fu_100_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_711)) begin
        if ((1'b1 == ap_condition_719)) begin
            grp_fu_100_p0 = abst_in_fu_184_p1;
        end else if ((1'b1 == ap_condition_713)) begin
            grp_fu_100_p0 = bitcast_ln55_fu_235_p1;
        end else begin
            grp_fu_100_p0 = 'bx;
        end
    end else begin
        grp_fu_100_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_711)) begin
        if ((1'b1 == ap_condition_719)) begin
            grp_fu_100_p1 = 64'd4607182418800017408;
        end else if ((1'b1 == ap_condition_713)) begin
            grp_fu_100_p1 = abst_in_fu_184_p1;
        end else begin
            grp_fu_100_p1 = 'bx;
        end
    end else begin
        grp_fu_100_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_104_ce = 1'b1;
    end else begin
        grp_fu_104_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_109_ce = 1'b1;
    end else begin
        grp_fu_109_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_114_ce = 1'b1;
    end else begin
        grp_fu_114_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_120_ce = 1'b1;
    end else begin
        grp_fu_120_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_126_ce = 1'b1;
    end else begin
        grp_fu_126_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_130_ce = 1'b1;
    end else begin
        grp_fu_130_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        if ((ap_predicate_pred752_state13 == 1'b1)) begin
            grp_fu_130_p0 = bitcast_ln66_1_fu_333_p1;
        end else if ((ap_predicate_pred747_state13 == 1'b1)) begin
            grp_fu_130_p0 = 64'd4611686018427387904;
        end else begin
            grp_fu_130_p0 = 'bx;
        end
    end else begin
        grp_fu_130_p0 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign abst_in_fu_184_p1 = t_fu_176_p3;

assign and_ln10_1_fu_317_p2 = (icmp_ln10_fu_305_p2 & and_ln10_fu_311_p2);

assign and_ln10_fu_311_p2 = (xor_ln10_fu_299_p2 & icmp_ln9_1_fu_281_p2);

assign and_ln46_fu_217_p2 = (icmp_ln46_fu_205_p2 & icmp_ln46_1_fu_211_p2);

assign and_ln9_1_fu_293_p2 = (xs_sign_fu_257_p3 & and_ln9_fu_287_p2);

assign and_ln9_fu_287_p2 = (icmp_ln9_fu_275_p2 & icmp_ln9_1_fu_281_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp68 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

always @ (*) begin
    ap_condition_120 = ((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_490 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_499 = ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_523 = ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_612 = ((ap_enable_reg_pp0_iter22 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_617 = (((icmp_ln45_reg_384_pp0_iter2_reg == 1'd1) & (icmp_ln36_reg_380_pp0_iter2_reg == 1'd0)) | ((icmp_ln36_reg_380_pp0_iter2_reg == 1'd0) & (1'd1 == and_ln46_reg_388_pp0_iter2_reg)));
end

always @ (*) begin
    ap_condition_653 = ((tmp_2_fu_135_p2 == 1'd0) & (icmp_ln45_fu_199_p2 == 1'd0) & (icmp_ln36_fu_193_p2 == 1'd0) & (1'd0 == and_ln46_fu_217_p2));
end

always @ (*) begin
    ap_condition_711 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0));
end

always @ (*) begin
    ap_condition_713 = ((tmp_2_fu_135_p2 == 1'd1) & (icmp_ln45_fu_199_p2 == 1'd0) & (icmp_ln36_fu_193_p2 == 1'd0) & (1'd0 == and_ln46_fu_217_p2));
end

always @ (*) begin
    ap_condition_719 = (((icmp_ln45_fu_199_p2 == 1'd1) & (icmp_ln36_fu_193_p2 == 1'd0)) | ((icmp_ln36_fu_193_p2 == 1'd0) & (1'd1 == and_ln46_fu_217_p2)));
end

always @ (*) begin
    ap_condition_871 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_00001));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_expx_reg_60 = 'bx;

assign ap_phi_reg_pp0_iter0_resultf_3_reg_72 = 'bx;

always @ (*) begin
    ap_predicate_op68_call_state3 = ((tmp_2_reg_392_pp0_iter1_reg == 1'd1) & (icmp_ln45_reg_384_pp0_iter1_reg == 1'd0) & (icmp_ln36_reg_380_pp0_iter1_reg == 1'd0) & (1'd0 == and_ln10_1_reg_422) & (1'd0 == and_ln9_1_reg_418) & (1'd0 == and_ln46_reg_388_pp0_iter1_reg));
end

always @ (*) begin
    ap_predicate_op68_call_state3_state2 = ((tmp_2_reg_392 == 1'd1) & (icmp_ln45_reg_384 == 1'd0) & (1'd0 == and_ln10_1_fu_317_p2) & (1'd0 == and_ln9_1_fu_293_p2) & (1'd0 == and_ln46_reg_388) & (icmp_ln36_reg_380 == 1'd0));
end

assign ap_return = ((din_sign_reg_366_pp0_iter22_reg[0:0] == 1'b1) ? bitcast_ln83_1_fu_355_p1 : ap_phi_mux_resultf_3_phi_fu_76_p10);

assign bitcast_ln55_fu_235_p1 = or_ln55_fu_229_p2;

assign bitcast_ln66_1_fu_333_p1 = xor_ln66_fu_327_p2;

assign bitcast_ln66_fu_323_p1 = expx_reg_60_pp0_iter11_reg;

assign bitcast_ln83_1_fu_355_p1 = xor_ln83_fu_349_p2;

assign bitcast_ln83_fu_345_p1 = ap_phi_mux_resultf_3_phi_fu_76_p10;

assign data_1_fu_253_p1 = x_3_fu_246_p3;

assign data_fu_146_p1 = t_in;

assign din_exp_fu_158_p4 = {{data_fu_146_p1[62:52]}};

assign din_sig_fu_168_p1 = data_fu_146_p1[51:0];

assign grp_exp_generic_double_s_fu_89_ap_start = grp_exp_generic_double_s_fu_89_ap_start_reg;

assign icmp_ln10_fu_305_p2 = ((xs_exp_1_fu_265_p4 < 11'd997) ? 1'b1 : 1'b0);

assign icmp_ln36_fu_193_p2 = ((din_exp_fu_158_p4 == 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln38_fu_240_p2 = ((din_sig_fu_168_p1 != 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_199_p2 = ((din_exp_fu_158_p4 < 11'd968) ? 1'b1 : 1'b0);

assign icmp_ln46_1_fu_211_p2 = ((din_sig_fu_168_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_205_p2 = ((din_exp_fu_158_p4 == 11'd968) ? 1'b1 : 1'b0);

assign icmp_ln54_fu_223_p2 = ((din_exp_fu_158_p4 < 11'd1023) ? 1'b1 : 1'b0);

assign icmp_ln9_1_fu_281_p2 = ((xs_exp_1_fu_265_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln9_fu_275_p2 = ((xs_exp_1_fu_265_p4 < 11'd996) ? 1'b1 : 1'b0);

assign or_ln55_fu_229_p2 = (t_fu_176_p3 | 64'd9223372036854775808);

assign select_ln38_fu_338_p3 = ((icmp_ln38_reg_406_pp0_iter21_reg[0:0] == 1'b1) ? 64'd9223372036854775807 : 64'd4607182418800017408);

assign t_fu_176_p3 = {{1'd0}, {trunc_ln479_fu_172_p1}};

assign trunc_ln479_fu_172_p1 = data_fu_146_p1[62:0];

assign x_3_fu_246_p3 = ((icmp_ln54_reg_396[0:0] == 1'b1) ? grp_fu_100_p2 : grp_fu_104_p2);

assign xor_ln10_fu_299_p2 = (xs_sign_fu_257_p3 ^ 1'd1);

assign xor_ln66_fu_327_p2 = (bitcast_ln66_fu_323_p1 ^ 64'd9223372036854775808);

assign xor_ln83_fu_349_p2 = (bitcast_ln83_fu_345_p1 ^ 64'd9223372036854775808);

assign xs_exp_1_fu_265_p4 = {{data_1_fu_253_p1[62:52]}};

assign xs_sign_fu_257_p3 = data_1_fu_253_p1[32'd63];

always @ (posedge ap_clk) begin
    abst_in_reg_371[63] <= 1'b0;
    abst_in_reg_371_pp0_iter1_reg[63] <= 1'b0;
end

endmodule //Lenet_HW_generic_tanh_double_s
